#!/bin/sh

list_daily_reports() {
    # Show given user's daily repots this month
    list_tag_items_all "日報/$(date +%Y/%m)" | grep $1 | sort | cut -d, -f2-
}

# Check number of given arguments
if [ $# -ne 1 ]
then
    echo "Usage: list_daily_reports.sh USERNAME"
    echo "  Ex.: list_daily_reports.sh yasulab"
    exit 1
fi

# Exec with given arguments if ready
list_daily_reports $@
